In [44]:
import numpy as np
import pandas as pd
import gensim
import os
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [45]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [46]:
story = []
for filename in os.listdir("E:/Assingment/Python Project/Game Of Thrones/Data"):

    f = open(os.path.join("E:/Assingment/Python Project/Game Of Thrones/Data", filename))
    corpus = f.read()

    raw_sent = sent_tokenize(corpus)
    
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [47]:
len(story)

145020

In [48]:
# All sentence are tokenize as mord
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [49]:
model = gensim.models.Word2Vec(window = 10, min_count = 2)

In [50]:
model.build_vocab(story)

In [51]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6569685, 8628190)

In [52]:
model.wv.most_similar('daenerys')

[('stormborn', 0.800312340259552),
 ('targaryen', 0.7858951091766357),
 ('queen', 0.735930860042572),
 ('myrcella', 0.7356897592544556),
 ('princess', 0.735521137714386),
 ('viserys', 0.7259718775749207),
 ('elia', 0.6986185312271118),
 ('rhaegar', 0.6819941401481628),
 ('joffrey', 0.6817288994789124),
 ('unburnt', 0.6808362007141113)]

In [53]:
model.wv.doesnt_match(['jon', 'rikon', 'arya', 'sansa', 'bran'])

'jon'

In [54]:
# Vector representation
model.wv['king']

array([ 1.1437025 ,  0.35067835,  0.17739105,  1.0946084 , -0.97487813,
       -0.11202899, -0.56083536,  0.23142624, -0.91570634,  0.5027311 ,
       -0.78764224,  0.4195598 ,  0.37322325,  2.9085853 , -2.2046905 ,
       -1.4559739 ,  0.46064726,  2.9080045 ,  2.4563398 ,  0.70017606,
        1.5094241 , -1.5184791 ,  2.4360604 , -3.587201  , -2.732361  ,
        3.2725337 , -2.0107243 , -1.089768  ,  1.5575289 ,  0.565759  ,
       -2.437194  ,  0.2341967 ,  0.90078795, -2.48994   ,  3.111185  ,
       -3.353291  , -2.4177928 , -0.17554836, -0.92818886, -1.361721  ,
       -2.3615785 ,  1.9854301 ,  2.6497324 , -0.07664599, -0.9429668 ,
       -2.276815  ,  0.5767569 , -2.333045  ,  4.388965  , -2.8090203 ,
       -2.4317105 ,  0.10149442, -1.0577363 , -4.5901937 ,  3.9797025 ,
       -2.0538068 ,  0.47467184,  2.097472  ,  1.1278131 ,  0.76513475,
        0.6859904 ,  0.52166   , -0.19591972,  0.88550466,  1.0619099 ,
        0.954916  , -0.5057155 ,  0.6767633 ,  0.6287762 , -0.90

In [55]:
model.wv['king'].shape

(100,)

In [56]:
model.wv.similarity('arya', 'sansa')

0.8545062

In [57]:
model.wv.similarity('cersei', 'sansa')

0.7657412

In [58]:
model.wv.similarity('tywin', 'sansa')

0.26393506

In [59]:
# Dimension of vectors - indexs
model.wv.get_normed_vectors()

array([[-0.12132154, -0.05359378,  0.146728  , ..., -0.1259287 ,
        -0.00345175,  0.10227226],
       [-0.11619111, -0.1885254 ,  0.0769513 , ...,  0.06160102,
         0.07477004,  0.01945799],
       [ 0.15790734,  0.00295269, -0.10511857, ..., -0.02653498,
         0.004055  , -0.04983046],
       ...,
       [ 0.0863504 ,  0.01509117,  0.04209635, ..., -0.05730309,
         0.08181345, -0.19688545],
       [-0.06145753,  0.07975351,  0.13290824, ..., -0.02043917,
         0.14231522, -0.07041934],
       [-0.08620788,  0.08207159,  0.09131005, ..., -0.06212388,
         0.11124227, -0.09402774]], dtype=float32)

In [60]:
model.wv.get_normed_vectors().shape

(17453, 100)

In [61]:
# converting index to word
y = model.wv.index_to_key

In [62]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'still',
 'face',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [63]:
from sklearn.decomposition import PCA

In [64]:
# Reduce the dimension from 100 to  3
pca = PCA(n_components=3)

In [65]:
x = pca.fit_transform(model.wv.get_normed_vectors())

In [66]:
x[:5]

array([[-0.13456453,  0.6075723 , -0.03881173],
       [-0.16798083,  0.3614755 ,  0.03691614],
       [ 0.30600417,  0.5527298 ,  0.20862111],
       [ 0.00449624,  0.39419374, -0.14382386],
       [ 0.12586984,  0.5426256 ,  0.26731047]], dtype=float32)

In [67]:
x.shape

(17453, 3)

In [71]:
import plotly.express as px
fig = px.scatter_3d(x[:500], x=0, y=1, z=2, color=y[:500])
fig.show()

In [72]:
import plotly.express as px
fig = px.scatter_3d(x[200 : 300], x=0, y=1, z=2, color=y[200 : 300])
fig.show()